config/routes.rb
Rails.application.routes.draw do
  root to: 'artists#index'


  resources :artists do
    resources :songs
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy

  validates :name,       presence: true, uniqueness: true
  has_one :image, dependent: :destroy

end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :artist

  mount_uploader :source, ImageUploader

end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  validates :name,       presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
  class ArtistsController < ApplicationController
  before_action :set_artist, except: [:index, :new, :create, :delete_all_songs]

  def index
    @artists = Artist.all
  end

  def show
    @song = Song.new
    @song.artist_id = @artist.id
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      @artist.create_image(source: source_params)

      redirect_to @artist, notice: "Artist created"
    else
      render :new
    end
  end

  def edit; end

  def update
    if @artist.update(artist_params)
      @artist.create_image(source: source_params)

      redirect_to @artist, notice: "Artist updated"
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy

    redirect_to root_path, notice: "Delete success"
  end

  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def source_params
    params[:source].present? ? params.require(:source) : []
  end

  def artist_params
    params
      .require(:artist)
      .permit(
        :name
      )
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, only: [:destroy]


  def new
    @song = @artist.songs.new
  end

  def create
    @song = @artist.songs.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @artist, notice: "Added #{@song.name} to #{@artist.name}" }
        format.json { render json: @song, status: :created }
      else
        format.html { redirect_to @artist }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to @artist, notice: 'Song deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params
      .require(:song)
      .permit(
        :name
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%=render "shared/validation_errors", errors: @artist.errors%>


<%= form_for @artist, html: { multipart: true } do |f| %>
  <div class="form-group">
    <label>Artist name</label>
    <%= f.text_field :name, placeholder: "Artist name", class: "form-control" %>
  </div>

  <div class="form-group">

  <span class="btn btn-default">
    <p>Upload Photos</p>
    <%= image_tag @artist.image.source.thumbnail if @artist.image.present?%>
    <hr>
    <%= file_field_tag "source", type: :file %>
  </span>
</div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Back", @artist, class: "btn btn-default" %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Edit 
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/artists/index.html.erb
<% @artists.each do |artist| %>
  <p>
    <%= link_to artist.name, artist%>
  </p>





<%end%>
<%= link_to "Add artist", new_artist_path(@artist), class: "btn btn-primary" %>

app/views/artists/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Add new song
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/artists/show.html.erb
<div class="artist-container">
  <div class="artist-image" style="background-image: url('<%= @artist.image.source%>');"></div>

  <div class="artist-info">

    <h1><%= @artist.name %></h1>

    <%= link_to "Update artist",
          edit_artist_path(@artist),
                class:        "custom-btn btn" %>
    <%= link_to 'Delete',
          artist_path(@artist),
                class:        "btn btn-danger",
                method:       :delete,
                data:         { confirm: 'Are you sure?' } %>
  </div>
</div>


<a class="btn btn-danger"
  data-confirm="Are you sure?"
  id="delete-all-songs">
    <span class="glyphicon glyphicon-trash"></span>
    Remove all songs
</a>


<table class="table" id="artistSongs">
  <tr>
    <th style="padding: 20px;" colspan="2">Songs</th>
  </tr>
    <% @artist.songs.each do | song |  %>
    <tr data-id=<%=song.id%>>
      <td style="padding: 20px;"><%= song.name %></td>
      <td style="text-align: right;">
        <a class="trashcan glyphicon glyphicon-trash song-delete" id="song-<%=song.id%>"></a>
    <% end%>
</table>


<%= render "shared/form", song: @song %>
<%= link_to "Back", root_path, class: "btn btn-default" %>


<%=# link_to '',
  #'javascript:;',
  #      class:        "btn btn-danger glyphicon glyphicon-trash song-delete",
  #      method:       :delete,
  #      data:         { confirm: 'Are you sure?' },
  #      id:           "song-#{song.id}"
        %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700,900" rel="stylesheet">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>


    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.min.js' %>

    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |name, msg| -%>
         <%= content_tag :div, msg, class: "alert alert-success" %>
    <% end -%>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_form.html.erb
<%= form_for [@artist, @song] do |f| %>
  <div class="form-group <%= @song.errors.any? ? 'has-error' : '' %>" id="formgroup-song">
    <%= f.text_field :name, placeholder: "Song name", class: 'form-control' %>

    <% if @song.errors.any? %>
      <% @song.errors.full_messages.each do |message| %>
        <span class="help-block"><%= message %></span>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/shared/_validation_errors.html.erb
<% if errors.any?%>
  <div class="alert alert-warning">
    <strong>Warning!</strong>
    <p><br></p>
    <%errors.full_messages.each do |error| %>
    <p><%=error%></p>
    <%end%>
  </div>
<%end%>

app/views/songs/_form.html.erb
<%=render "shared/validation_errors", errors: @song.errors%>


<%= form_for [@artist, @song] do |f| %>
  <div class="form-group">
    <label>Song name</label>
    <%= f.text_field :name, placeholder: "Song name", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Back", @artist, class: "btn btn-default" %>
  </div>
<% end %>

app/views/songs/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Add new song
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>